# Generated by Django 5.2.7 on 2026-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.JSONField(default=list)),
                ('keys', models.JSONField(default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
