# Generated by Django 5.2.7 on 2026-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftresAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_id', models.CharField(max_length=32, unique=True)),
                ('instance', models.CharField(blank=True, max_length=64)),
                ('raid_date', models.BigIntegerField(blank=True, null=True)),
                ('reserve_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
