# Generated by Django 4.2.30 on 2026-08-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_softresaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtieshHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(default='armory', max_length=16)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaidComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_id', models.CharField(max_length=32, unique=True)),
                ('instance', models.CharField(blank=True, max_length=64)),
                ('groups', models.JSONField(default=list)),
                ('bench', models.JSONField(default=list)),
                ('overrides', models.JSONField(default=dict)),
                ('pins', models.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
