# Generated by Django 4.2.30 on 2026-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_atieshholder_raidcomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidcomp',
            name='stack_tanks',
            field=models.BooleanField(default=False),
        ),
    ]
