# Generated by Django 5.2.7 on 2026-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_raidcomp_stack_tanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='softresaudit',
            name='reserves',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
